1 - Ruby on Rails/S11 - projet 2 semaines (équipe)/formatech-main/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :fields
  resources :tags
  root 'static_pages#index'
  resources :comments

  resources :favorites

  resources :courses do
    member do
      put 'like' => 'courses#vote'
    end
    resources :pictures, only: %i[create update]
  end

  devise_for :instructors

  resources :instructors do
    resources :logos, only: %i[create update]
  end

  devise_for :users

  # resources :instructors, :path => '/:nickname' do
  #   resources :logos, :only =>[:create, :update]
  # end

  resources :users do
    resources :avatars, only: %i[create update]
  end

  resources :instructor_carts
  resources :instructor_orders

  resources :charges, only: %i[new create destroy]
  scope '/charges' do
    get 'cancel', to: 'charges#cancel', as: 'charges_cancel'
    get 'success', to: 'charges#success', as: 'charges_success'
  end

  # resources :users, :except => [:show] do
  #   resources :avatars, :only =>[:create, :update]
  # end

  # resources :users, only: :show, param: :slug do
  #   resources :avatars, :only =>[:create, :update]
  # end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

1 - Ruby on Rails/S11 - projet 2 semaines (équipe)/formatech-main/app/views/layouts/_footer.html.erb
<div style="margin-top:100px"></div>
<footer>
<div style="margin-top:20px"></div>
<br>
<div class="container">
  <div class="row">
    <div class="col-sm">
     <h6 class="text-uppercase fw-bold mb-4 text-light">Get connected with us on social media</h6>
    </div>
    <div class="col-sm">
      <p>
        <a class="btn btn-primary" id="footer-icon" style="background-color: #ac2bac; border: 1px solid white;" href="https://www.youtube.com/watch?v=MWJqBEV1his" target="_blank"><i class="fab fa-instagram"></i></a>
      </p>
    </div>
    <div class="col-sm">
      <p>
        <a class="btn btn-primary" id="footer-icon" style="background-color: #55acee; border: 1px solid white" href="https://www.youtube.com/watch?v=jr-WIrDd2Oc" target="_blank"><i class="fab fa-twitter"></i></a>
      </p>
    </div>
    <div class="col-sm">
      <p>
        <a class="btn btn-primary" id="footer-icon" style="background-color: #3b5998; border: 1px solid white" href="https://www.youtube.com/watch?v=xO4LaAHJqxw" target="_blank"><i class="fab fa-facebook-f"></i></a>
      </p>
    </div>
    <div class="col-sm">
      <p>
        <a class="btn btn-primary" id="footer-icon" style="background-color: #0274b3; border: 1px solid white" href="https://www.youtube.com/watch?v=NsLKQTh-Bqo" target="_blank"><i class="fab fa-linkedin"></i></a>
      </p>
    </div>
    <div class="col-sm">
      <p>
        <a class="btn btn-primary" id="footer-icon" style="background-color: #3b5998; border: 1px solid white" href="https://github.com/Raphael1894/formatech" target="_blank"><i class="fab fa-github-square"></i></a>
      </p>
    </div>
  </div>
</div>
  <div class="text-center p-4 text-light" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="/">https://formatech-org.herokuapp.com/</a>
  </div>
</footer>

1 - Ruby on Rails/S11 - projet 2 semaines (équipe)/formatech-main/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <img src="/assets/formatech_logo/logo_transparent.png" class="logo-brand" alt="Logo Formatech">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav ">
        <li class="nav-item active">
          <%= link_to 'Home', root_path, class:"nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Courses', courses_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
      <%if user_signed_in? || instructor_signed_in?%>
      <%else%>
        <div class="content">
          <div class="content__container">
              <p class="content__container__text">Hello</p>
            <ul class="content__container__list">
              <li class="content__container__list__item">world !</li>
              <li class="content__container__list__item">instructors !</li>
              <li class="content__container__list__item">users !</li>
              <li class="content__container__list__item">everybody !</li>
            </ul>
          </div>
        </div>
      <%end%>
      <div class="d-flex justify-content-end">
        <ul class="navbar-nav ">      
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
            <div class="dropdown-menu dropdown-menu-right">                
              <%= link_to "Account", user_path(current_user), class:"dropdown-item" %>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
            </div>  
          </li>
          <li> 
            <%if current_user.avatar.attached?%> <%= image_tag current_user.avatar, alt: 'image', class:"avatar-image rounded-circle" %> <% end %> 
          </li>
        <% elsif instructor_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
            <div class="dropdown-menu dropdown-menu-right">                
              <%= link_to "Account", instructor_path(current_instructor), class:"dropdown-item" %></a>
              <%= link_to "Sign out", destroy_instructor_session_path, class:"dropdown-item", method: :delete %></a>
            </div>  
          </li>
          <li>
            <%if current_instructor.logo.attached?%> <%= image_tag current_instructor.logo, alt: 'image', class: "avatar-image rounded-circle" %> <% end %>
          </li>  
            <span class="badge badge-danger badge-counter"> 
              <%= link_to "Cart", instructor_carts_path, class:"fas fa-shopping-cart fa-fw" %>
              <br> <br> 
              <%= InstructorCart.all.where(instructor_id: current_instructor).count %> 
            </span>
              <div style="margin-right: 2em"></div>
          </li>

        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sign as user</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Sign in", new_user_session_path, class:"dropdown-item" %>
              <%= link_to "Sign up", new_user_registration_path, class:"dropdown-item" %>
            </div>  
          </li>
           <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Sign as instructor</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Sign in", new_instructor_session_path, class:"dropdown-item" %>
              <%= link_to "Sign up", new_instructor_registration_path, class:"dropdown-item" %>
            </div>  
          </li>
        <% end %>
        </ul>
      </div>
  </div>
</nav>

1 - Ruby on Rails/S11 - projet 2 semaines (équipe)/formatech-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Formatech</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://kit.fontawesome.com/6773662ef5.js" crossorigin="anonymous"></script>
  </head>

  <body style="background-color: #E6E8E6;">
    <%= render "layouts/navbar" %>
      <%= yield %>
    <%= render "layouts/footer" %>
  </body>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>